openapi: 3.0.0
info:
  version: '1.0'
  title: Forget-password documentation
  description: ''
paths:
  /customers/forgot-password:
    get:
      summary: email exists
      description: checking the database for the entered email.
      tags: 
        - Forgot-pssword Journey
      parameters:
        - in: query
          name: email
          required: true
          schema:
            type: string
            format: string
            example: 'test@gmail.com'
            
          
      responses:
        200:
          description: Email exists
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/ng-forgot-password'
                    
            
        400:
          description: Email does'nt exists
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
            
        404:
          description: User not found
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/NotFoundError'     
                
                
components:
  schemas:
    ng-forgot-password:
      type: object
      description: user Object
      properties:
        emailId:
          type: string
          pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
          example: 'test@gmail.com'
        message: 
          type: string
          example: email exists in database
          
    
    BadRequestError:
      type: object
      properties:
        errors:
            type: array
            items:
              type: object
              properties:
                message:
                  type: string
                  example: Invalid request
                code:
                  type: integer
                  example: 400        
    
    NotFoundError:
      type: object
      properties:
        errors:
            type: array
            items:
              type: object
              properties:
                message:
                  type: string
                  example: 'Not found'
                code:
                  type: integer
                  example: 404
    
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/RAHULRAJJ6580/forgot-password/1.0